apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: otel-demo
spec:
  flagSpec:
    flags:
      productCatalogFailure:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "on"
      recommendationServiceCacheFailure:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
      adServiceManualGc:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
      adServiceHighCpu:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
      adServiceFailure:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
        targeting: {
          "fractional": [
            {
              "var": "session"
            },
            [
              "on",
              10
            ],
            [
              "off",
              90
            ]
          ]
        }
      cartServiceFailure:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
      paymentServiceFailure:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
      paymentServiceUnreachable:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
      loadgeneratorFloodHomepage:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
