apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: otel-demo
spec:
  flagSpec:
    flags:
      adServiceFailure:
        state: "ENABLED"
        variants:
          "adServiceFailure": "ADSERVICEFAILURE"
        defaultVariant: "adServiceFailure"
        targeting: {}
      cartServiceFailure:
        state: "DISABLED"
        variants:
          "cartServiceFailure": "CARTSERVICEFAILURE"
        defaultVariant: "cartServiceFailure"
        targeting: {}
      paymentServiceFailure:
        state: "DISABLED"
        variants:
          "paymentServiceFailure": "PAYMENTSERVICEFAILURE"
        defaultVariant: "paymentServiceFailure"
        targeting: {}
