apiVersion: batch/v1
kind: Job
metadata:
  name: annotate-ns
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: annotatejob
      containers:
      - name: uid-annotation-ns
        image: "bitnami/kubectl:latest"
        command:
          - kubectl
          - annotate
          - ns
          - {{ .Release.Namespace }}
          - openshift.io/sa.scc.uid-range=101/65532
          - --overwrite
      - name: groups-annotation-ns
        image: "bitnami/kubectl:latest"
        command:
          - kubectl
          - annotate
          - ns
          - {{ .Release.Namespace }}
          - openshift.io/sa.scc.supplemental-groups=101/65532
          - --overwrite
