apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-demo
spec:
  config: |
    exporters:
      debug:
      otlp:
        endpoint: tempo-simplest-distributor:4317
        tls:
          insecure: true
    processors:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    service:
      pipelines:
        traces:
          exporters:
          - otlp
          - debug
          processors:
          receivers:
          - otlp
        metrics:
          exporters:
          - debug
          processors:
          receivers:
          - otlp
        logs:
          exporters:
          - debug
          processors:
          receivers:
          - otlp