apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-demo
spec:
  config:
    exporters:
      otlp:
        endpoint: tempo-simplest-distributor:4317
        tls:
          insecure: true
      logging: {}
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    service:
      pipelines:
        traces:
          exporters:
          - otlp
          - logging
          processors: []
          receivers:
          - otlp
        metrics:
          exporters:
          - logging
          processors: []
          receivers:
          - otlp
        logs:
          exporters:
          - logging
          processors: []
          receivers:
          - otlp